<?php
namespace frontend\widgets;

use yii\base\Widget;

class CategoryWidgets extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}